# Generated by Django 4.1 on 2022-08-13 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Startup",
            fields=[
                ("startup_id", models.AutoField(primary_key=True, serialize=False)),
                ("user_type", models.IntegerField(default=0)),
                ("name", models.CharField(default="", max_length=50)),
                ("tagname", models.CharField(default="", max_length=200)),
                ("about", models.CharField(default="", max_length=2000)),
                ("comapany_type", models.CharField(default="", max_length=50)),
                ("market_cap", models.IntegerField(default=0)),
                ("netsales", models.IntegerField(default=0)),
                ("revenue", models.IntegerField(default=0)),
                ("profit_after_tax", models.IntegerField(default=0)),
                ("profit_growth", models.IntegerField(default=0)),
                ("company_mission", models.CharField(default=0, max_length=2000)),
                ("fund_to_be_raised", models.IntegerField(default=0)),
                ("hiring_details", models.CharField(default="", max_length=2000)),
                ("job_vacancy", models.IntegerField(default=0)),
                ("completion_status", models.IntegerField(default=0)),
                ("website_link", models.CharField(default=0, max_length=100)),
                ("linked_link", models.CharField(default=0, max_length=100)),
                ("twitter_link", models.CharField(default=0, max_length=100)),
            ],
        ),
    ]
