# Generated by Django 4.1 on 2022-09-24 16:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("riseup", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Request",
            fields=[
                ("table_id", models.AutoField(primary_key=True, serialize=False)),
                ("user_type", models.IntegerField(default=0)),
                ("request_type", models.IntegerField(default=0)),
                ("description", models.CharField(default="", max_length=1000)),
                ("specific_link", models.CharField(default=0, max_length=200)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("status", models.IntegerField(default=0)),
                (
                    "startup_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="riseup.startup"
                    ),
                ),
                (
                    "user_name",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
