# Generated by Django 4.1 on 2022-08-13 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("riseup", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Investor",
            fields=[
                ("table_id", models.AutoField(primary_key=True, serialize=False)),
                ("user_type", models.IntegerField(default=0)),
                ("name", models.CharField(default="", max_length=50)),
                ("phone", models.CharField(default="", max_length=20)),
                ("description", models.CharField(default="", max_length=1000)),
                ("linkedln", models.CharField(default="", max_length=30)),
                ("email", models.EmailField(default="", max_length=254)),
                ("completion_status", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                ("table_id", models.AutoField(primary_key=True, serialize=False)),
                ("user_type", models.IntegerField(default=0)),
                ("name", models.CharField(default="", max_length=50)),
                ("age", models.IntegerField(default=0)),
                ("area", models.CharField(default="", max_length=100)),
                ("state", models.CharField(default="", max_length=100)),
                ("email", models.EmailField(default="", max_length=254)),
                ("phone", models.CharField(default="", max_length=20)),
                ("college", models.CharField(default="", max_length=100)),
                ("course", models.CharField(default="", max_length=100)),
                ("description", models.CharField(default="", max_length=1000)),
                ("completion_status", models.IntegerField(default=0)),
            ],
        ),
        migrations.RenameField(
            model_name="startup",
            old_name="linked_link",
            new_name="linkedin_link",
        ),
        migrations.AddField(
            model_name="startup",
            name="email",
            field=models.EmailField(default="", max_length=254),
        ),
    ]
