# Generated by Django 4.1 on 2022-08-13 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("riseup", "0002_investor_student_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="investor",
            name="username",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="startup",
            name="username",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="username",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
